<a href="https://colab.research.google.com/github/Mahendran1987-boob/Cross_Market_Analysis_Crypto-_Oil_-_Stocks/blob/main/Cross_Market_Analysis_Crypto%2C_Oil_%26_Stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [2]:
name = "Mahendran S"
print(f"My name is {name}")

My name is Mahendran S

In [3]:
all_records = []#250 + 250 + 250 (750-1250)
import requests  # Use string formating, and for loop and scroll through 5 pages to collect data

url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250&order=market_cap_desc&page=3&sparkline=False"

response = requests.get(url)
 # 200 means your request was success
if response.status_code == 200:
  data = response.json()
  #all_records.extend(data)

  # while running this code, if you face, rate limit exceeded error, wait for 10 or 15 mins and then
  #again execute it

In [4]:
import requests
import pandas as pd
all_records = []

# 250 records per page × 5 pages = 1250 records
for i in range(1,6):
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250&order=market_cap_desc&page={i}&sparkline=False"

    response = requests.get(url)

    if response.status_code == 200:
        data1 = response.json()
        all_records.extend(data1)

#print(data1)  # Should print 1250
ar = pd.DataFrame(data1)
ar = ar.rename(columns={'last_updated': 'Date'})
ar

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,Date
0,berachain-bera,bera,Berachain,https://coin-images.coingecko.com/coins/images...,0.476827,109447538,251,255115247,17186806.00,0.502522,...,5.350109e+08,NaN,14.830000,-96.78357,2025-02-06T14:16:01.862Z,0.349389,36.49784,2026-02-06T00:25:15.713Z,None,2026-03-27T02:24:22.554Z
1,tokenize-xchange,tkx,Tokenize Xchange,https://coin-images.coingecko.com/coins/images...,1.360000,109086830,252,136365360,4977.18,1.400000,...,1.000000e+08,1.000000e+08,50.430000,-97.29602,2025-01-03T19:12:43.038Z,0.111255,1125.70444,2019-04-28T00:00:00.000Z,"{'times': 3.6915415455874045, 'currency': 'usd...",2026-03-27T02:24:22.388Z
2,livepeer,lpt,Livepeer,https://coin-images.coingecko.com/coins/images...,2.150000,106681915,253,106681915,7390971.00,2.210000,...,4.968895e+07,NaN,99.030000,-97.83088,2021-11-09T16:58:44.554Z,0.354051,506.70215,2019-10-26T22:59:09.500Z,None,2026-03-27T02:24:22.646Z
3,societe-generale-forge-eurcv,eurcv,EUR CoinVertible,https://coin-images.coingecko.com/coins/images...,1.150000,106502165,254,106502165,10543734.00,1.160000,...,9.243348e+07,NaN,1.220000,-5.37844,2026-01-27T05:25:46.416Z,0.988513,16.60976,2025-02-04T22:15:33.361Z,None,2026-03-27T02:24:22.496Z
4,securitize-tokenized-aaa-clo-fund,stac,Securitize Tokenized AAA CLO Fund,https://coin-images.coingecko.com/coins/images...,1009.010000,106046595,255,106046595,0.00,1009.560000,...,1.050997e+05,NaN,1012.990000,-0.39273,2026-02-05T22:30:05.739Z,997.660000,1.13758,2026-02-06T00:15:06.823Z,None,2026-03-27T02:20:03.785Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,meet48,idol,MEET48,https://coin-images.coingecko.com/coins/images...,0.024026,42820111,495,114552582,4099037.00,0.024891,...,4.767829e+09,4.800000e+09,0.041778,-42.50245,2025-09-04T16:32:55.332Z,0.010342,132.26925,2025-08-01T01:56:18.076Z,None,2026-03-27T02:24:23.648Z
246,uchain-2,ucn,UCHAIN,https://coin-images.coingecko.com/coins/images...,427.240000,42766342,497,42766342,2593605.00,455.880000,...,1.000000e+05,1.000000e+05,1806.540000,-76.35194,2026-01-11T09:03:36.187Z,23.780000,1696.42426,2025-08-27T07:49:23.699Z,None,2026-03-27T02:24:23.584Z
247,frax-share,frax,Frax (prev. FXS),https://coin-images.coingecko.com/coins/images...,0.447428,42683312,499,44603845,1462415.00,0.459955,...,9.968150e+07,NaN,42.800000,-98.95437,2022-01-12T15:22:27.465Z,0.433406,3.25503,2026-03-26T07:21:24.575Z,None,2026-03-27T02:24:23.688Z
248,tellor,trb,Tellor Tributes,https://coin-images.coingecko.com/coins/images...,15.420000,42663631,500,43827492,8287625.00,15.870000,...,2.841339e+06,NaN,593.090000,-97.39811,2023-12-31T22:15:07.200Z,0.010014,154002.29219,2019-11-01T10:00:10.047Z,None,2026-03-27T02:24:23.680Z
249,ai-companions,aic,AI Companions,https://coin-images.coingecko.com/coins/images...,0.042644,42643543,498,42643543,373501.00,0.044372,...,1.000000e+09,1.000000e+09,0.580508,-92.65244,2025-10-05T13:10:48.049Z,0.037514,13.69831,2024-11-11T08:25:53.573Z,None,2026-03-27T02:24:23.696Z

In [8]:
import requests
import pandas as pd
import time

all_records = []

for i in range(1, 6):   # 1 to 5 (5 pages)
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250&order=market_cap_desc&page={i}&sparkline=false"

    response = requests.get(url)

    print(f"Page {i} status:", response.status_code)

    if response.status_code == 200:
        data = response.json()
        print(f"Page {i} records:", len(data))
        all_records.extend(data)
    else:
        print("Error on page", i)

    time.sleep(1)   # Prevent rate limit

print("Total records:", len(all_records))
#print(data)
df = pd.DataFrame(all_records)
df

cc =  df[['id','symbol','name','current_price','market_cap','market_cap_rank','total_volume','circulating_supply','total_supply','ath','atl','last_updated']]
#cc = pd.DataFrame(cc)
cc = cc.rename(columns={'last_updated': 'Date'})
cc['Date'] = pd.to_datetime(cc['Date']).dt.strftime('%Y-%m-%d')

cc.head()
#cc = cc.rename(columns={'last_updated': 'Date'})
cc_copy = cc.copy()
cc_copy.to_csv("/content/drive/MyDrive/Cryptocurrencies.csv")
#print(df)   # Should show (750, number_of_columns)
df.head()         # View first 5 rows

Page 1 status: 200
Page 1 records: 250
Page 2 status: 200
Page 2 records: 250
Page 3 status: 429
Error on page 3
Page 4 status: 429
Error on page 4
Page 5 status: 429
Error on page 5
Total records: 500

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,68962.000000,1379567028201,1,1379567028201,5.269775e+10,70899.000000,...,2.000304e+07,2.100000e+07,126080.00,-45.30268,2025-10-06T18:57:42.558Z,67.810000,1.016008e+05,2013-07-06T00:00:00.000Z,None,2026-03-27T02:25:11.894Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2070.100000,249847592130,2,249847592130,1.835476e+10,2153.730000,...,1.206915e+08,NaN,4946.05,-58.14627,2025-08-24T19:21:03.333Z,0.432979,4.780078e+05,2015-10-20T00:00:00.000Z,"{'times': 39.12963454309574, 'currency': 'btc'...",2026-03-27T02:25:11.563Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999393,184107104081,3,189570794902,7.983953e+10,0.999636,...,1.896835e+11,NaN,1.32,-24.46370,2018-07-24T00:00:00.000Z,0.572521,7.456430e+01,2015-03-02T00:00:00.000Z,None,2026-03-27T02:25:14.515Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,630.270000,85943924731,4,85943924731,9.112300e+08,644.660000,...,1.363573e+08,2.000000e+08,1369.99,-53.99448,2025-10-13T08:41:24.131Z,0.039818,1.582794e+06,2017-10-19T00:00:00.000Z,None,2026-03-27T02:25:11.422Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.370000,83875239392,5,136708469239,2.639369e+09,1.410000,...,9.998570e+10,1.000000e+11,3.65,-62.50365,2025-07-18T03:40:53.808Z,0.002686,5.079924e+04,2014-05-22T00:00:00.000Z,None,2026-03-27T02:25:14.327Z

In [9]:
cc

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,Date
0,bitcoin,btc,Bitcoin,68962.000000,1379567028201,1,5.269775e+10,2.000304e+07,2.000304e+07,126080.000000,67.810000,2026-03-27
1,ethereum,eth,Ethereum,2070.100000,249847592130,2,1.835476e+10,1.206915e+08,1.206915e+08,4946.050000,0.432979,2026-03-27
2,tether,usdt,Tether,0.999393,184107104081,3,7.983953e+10,1.842166e+11,1.896835e+11,1.320000,0.572521,2026-03-27
3,binancecoin,bnb,BNB,630.270000,85943924731,4,9.112300e+08,1.363573e+08,1.363573e+08,1369.990000,0.039818,2026-03-27
4,ripple,xrp,XRP,1.370000,83875239392,5,2.639369e+09,6.134458e+10,9.998570e+10,3.650000,0.002686,2026-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...
495,meet48,idol,MEET48,0.024025,42820111,496,4.098798e+06,1.782229e+09,4.767829e+09,0.041778,0.010342,2026-03-27
496,uchain-2,ucn,UCHAIN,427.370000,42724456,497,2.597663e+06,1.000000e+05,1.000000e+05,1806.540000,23.780000,2026-03-27
497,frax-share,frax,Frax (prev. FXS),0.447343,42671752,498,1.462204e+06,9.538945e+07,9.968150e+07,42.800000,0.433406,2026-03-27
498,tellor,trb,Tellor Tributes,15.420000,42663607,499,8.273354e+06,2.765886e+06,2.841339e+06,593.090000,0.010014,2026-03-27
499,ai-companions,aic,AI Companions,0.042629,42643543,500,3.003850e+05,1.000000e+09,1.000000e+09,0.580508,0.037514,2026-03-27

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#df_copy.to_csv("/content/drive/MyDrive/coin_data.csv", index = False)
#df_copy = df.copy()

\# Top 3 Coins – Historical Prices

In [7]:
#Correct code
import pandas as pd
import requests

coin_ids = ['bitcoin', 'ethereum', 'tether']

all_prices = []

for coin in coin_ids:

    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart"

    params = {
        "vs_currency": "usd",
        "days": "365"
    }

    response = requests.get(url, params=params)
    r = response.json()

    df = pd.DataFrame(r['prices'], columns=['timestamp','price_usd'])

    df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
    df['coin_id'] = coin

    df = df[['coin_id','date','price_usd']]

    all_prices.append(df)

crypto_prices = pd.concat(all_prices, ignore_index=True)
crypto_prices["date"] = pd.to_datetime(crypto_prices["date"]).dt.date
crypto_prices
crypto_prices = pd.concat(all_prices, ignore_index=True)
crypto_prices["date"] = pd.to_datetime(crypto_prices["date"]).dt.date
crypto_prices
crypto_prices.head()

   coin_id        date     price_usd
0  bitcoin  2025-03-28  87227.271580
1  bitcoin  2025-03-29  84359.469155
2  bitcoin  2025-03-30  82679.172554
3  bitcoin  2025-03-31  82356.381112
4  bitcoin  2025-04-01  82514.093654

In [10]:
crypto_prices

      coin_id        date     price_usd
0     bitcoin  2025-03-28  87227.271580
1     bitcoin  2025-03-29  84359.469155
2     bitcoin  2025-03-30  82679.172554
3     bitcoin  2025-03-31  82356.381112
4     bitcoin  2025-04-01  82514.093654
...       ...         ...           ...
1093   tether  2026-03-24      0.999728
1094   tether  2026-03-25      0.999546
1095   tether  2026-03-26      0.999616
1096   tether  2026-03-27      0.999378
1097   tether  2026-03-27      0.999401

[1098 rows x 3 columns]

Oil Prices

In [ ]:
'''import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df.to_csv(r"/content/drive/MyDrive/oilprices.csv", index=False)
df = pd.DataFrame(oil_df)
#cc = cc.rename(columns={'last_updated': 'Date'})
df = df.rename(columns={'Price': 'price_usd'})
df'''

In [11]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/oilprices.csv")
df
df['Date'] = pd.to_datetime(df['Date'])# format='%d-%m-%Y')
filtered_df = df[
    (df['Date'] >= '2020-01-01') &
    (df['Date'] <= '2026-01-31')
]
filtered_df['Date'] = pd.to_datetime(filtered_df['Date']).dt.strftime('%Y-%m-%d')
filtered_df = filtered_df.rename(columns={'Price': 'price_usd'})
#filtered_df = filtered_df.rename(columns={"Price": "Price_usd"})
#oil_df = filtered_df.rename(columns={"price": "price_usd"}, inplace=True)
filtered_df.to_csv(r"/content/drive/MyDrive/oilprices1.csv", index=False)

/tmp/ipykernel_2234/1075808767.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Date'] = pd.to_datetime(filtered_df['Date']).dt.strftime('%Y-%m-%d')

In [12]:
filtered_df

             Date  price_usd
8569   2020-01-02      61.17
8570   2020-01-03      63.00
8571   2020-01-06      63.27
8572   2020-01-07      62.70
8573   2020-01-08      59.65
...           ...        ...
10084  2026-01-26      60.46
10085  2026-01-27      62.04
10086  2026-01-28      62.75
10087  2026-01-29      64.77
10088  2026-01-30      64.50

[1520 rows x 2 columns]

In [13]:
filtered_df.to_csv("oil_prices.csv",index = False) # after collecting all the data make sure to save it as a csv files

Stock Prices (Yahoo Finance API)

In [14]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2025-09-30"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()
#stocks_df.tail()

/tmp/ipykernel_2234/58905462.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [15]:
stocks_1 = stocks_df['^GSPC'].reset_index() # collect 3 ticker data similarly , add a new column ticker and then concat them.
# handle the  nulls
stocks_1["Ticker"] = "^GSPC"
stocks_1 = stocks_1.dropna(subset=['Close'])
stocks_1

Price,Date,Open,High,Low,Close,Volume,Ticker
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
5,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
1485,2025-09-23,6692.439941,6699.520020,6645.580078,6656.919922,5.633620e+09,^GSPC
1486,2025-09-24,6669.790039,6672.660156,6621.759766,6637.970215,5.459180e+09,^GSPC
1487,2025-09-25,6608.189941,6619.000000,6569.220215,6604.720215,5.874670e+09,^GSPC
1488,2025-09-26,6615.379883,6648.970215,6604.430176,6643.700195,5.103110e+09,^GSPC
1489,2025-09-29,6661.580078,6677.310059,6644.490234,6661.209961,5.358760e+09,^GSPC

In [16]:
stocks_2 = stocks_df['^IXIC'].reset_index() # collect 3 ticker data similarly , add a new column ticker and then concat them.
# handle the  nulls
stocks_2["Ticker"] = "^IXIC"
stocks_2 = stocks_2.dropna(subset=['Close'])
stocks_2

Price,Date,Open,High,Low,Close,Volume,Ticker
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,^IXIC
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,^IXIC
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,^IXIC
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,^IXIC
5,2020-01-08,9068.030273,9168.889648,9059.379883,9129.240234,2.472620e+09,^IXIC
...,...,...,...,...,...,...,...
1485,2025-09-23,22782.720703,22785.130859,22539.039062,22573.470703,9.822620e+09,^IXIC
1486,2025-09-24,22656.019531,22657.449219,22397.000000,22497.859375,9.184030e+09,^IXIC
1487,2025-09-25,22318.769531,22456.779297,22185.869141,22384.699219,9.960330e+09,^IXIC
1488,2025-09-26,22403.269531,22488.179688,22285.439453,22484.070312,8.488400e+09,^IXIC
1489,2025-09-29,22605.300781,22704.900391,22536.050781,22591.150391,9.046720e+09,^IXIC

In [17]:
stocks_3 = stocks_df['^NSEI'].reset_index() # collect 3 ticker data similarly , add a new column ticker and then concat them.
# handle the  nulls
stocks_3['Ticker'] = "^NSEI"
stocks_3 = stocks_3.dropna(subset=['Close'])
stocks_3

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI
...,...,...,...,...,...,...,...
1485,2025-09-23,25209.000000,25261.900391,25084.650391,25169.500000,299200.0,^NSEI
1486,2025-09-24,25108.750000,25149.849609,25027.449219,25056.900391,244400.0,^NSEI
1487,2025-09-25,25034.500000,25092.699219,24878.300781,24890.849609,342500.0,^NSEI
1488,2025-09-26,24818.550781,24868.599609,24629.449219,24654.699219,291500.0,^NSEI
1489,2025-09-29,24728.550781,24791.300781,24606.199219,24634.900391,394400.0,^NSEI

In [19]:
all_stocks = pd.concat([stocks_1, stocks_2, stocks_3])
all_stocks['Date'] = pd.to_datetime(all_stocks['Date']).dt.strftime('%Y-%m-%d')

In [20]:
all_stocks

Price,Date,Open,High,Low,Close,Volume,Ticker
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
5,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
1485,2025-09-23,25209.000000,25261.900391,25084.650391,25169.500000,2.992000e+05,^NSEI
1486,2025-09-24,25108.750000,25149.849609,25027.449219,25056.900391,2.444000e+05,^NSEI
1487,2025-09-25,25034.500000,25092.699219,24878.300781,24890.849609,3.425000e+05,^NSEI
1488,2025-09-26,24818.550781,24868.599609,24629.449219,24654.699219,2.915000e+05,^NSEI
1489,2025-09-29,24728.550781,24791.300781,24606.199219,24634.900391,3.944000e+05,^NSEI

In [21]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [22]:
import sqlite3
conn = sqlite3.connect("ds.db")
cursor = conn.cursor()

In [23]:
cc.to_sql("Cryptocurrencies",if_exists="replace",con =conn)

500

In [24]:
crypto_prices.to_sql("Crypto_price",if_exists="replace",con =conn)

1098

In [25]:
filtered_df.to_sql("oil_prices",if_exists="replace",con =conn)

1520

In [26]:
all_stocks.to_sql("stock_prices",if_exists="replace",con =conn)

4309

In [ ]:
# 1. create 4 tables
# 2. Insert 4 dataframe into sql(4 tables) usinf df.iterrows and cursor
# 3. Queries

Streamlit demo

In [76]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-03-27 02:40:25--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-27 02:40:25--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-27T03%3A38%3A03Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-27T02%3A37%3A27Z&ske=2026-03-27T03%3A38%3A03Z&sks=b&skv=2018-11-09&sig=R5%2FIeDXkBVFtT%2FrLQkHrdQsNnJ%2FEjkjCZvHhhiXCm%2F8%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDU4MDg5NywibmJmIjoxNzc0NTc5MDk3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.QrWK0F74eNA3LeJ4-SPAmx5tMHylaCSEEaDSI6RM6tw&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-27 02:40:25--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-27T03%3A38%3A03Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-27T02%3A37%3A27Z&ske=2026-03-27T03%3A38%3A03Z&sks=b&skv=2018-11-09&sig=R5%2FIeDXkBVFtT%2FrLQkHrdQsNnJ%2FEjkjCZvHhhiXCm%2F8%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDU4MDg5NywibmJmIjoxNzc0NTc5MDk3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.QrWK0F74eNA3LeJ4-SPAmx5tMHylaCSEEaDSI6RM6tw&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64.2’

cloudflared-linux-a 100%[===================>]  37.83M   227MB/s    in 0.2s

2026-03-27 02:40:25 (227 MB/s) - ‘cloudflared-linux-amd64.2’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

Code

In [77]:
!pip install streamlit-option-menu

Requirement already satisfied: streamlit-option-menu in /usr/local/lib/python3.12/dist-packages (0.4.0)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)

In [78]:
%%writefile app.py

import streamlit as st
import pandas as pd

from streamlit_option_menu import option_menu
import sqlite3
conn = sqlite3.connect("ds.db")
cursor = conn.cursor()
st.title("💰🛢️📈Cross-Market Analysis")

with st.sidebar:
    selected = option_menu("Main Menu", ["Home", 'Filters',"Queries","Crypto Analysis"],
        icons=['house', 'gear'], menu_icon="cast", default_index=1)

if selected == "Home":
    st.write("This is my home page")
    st.write("Oil Market (e.g., Crude Oil)")
    st.write("Influences the global economy. When oil prices rise, costs increase for industries, which can reduce company profits.")
    st.write("Stock Market (e.g., S&P 500, NIFTY 50)")
    st.write("Reflects economic health. Rising oil prices often negatively impact stocks, especially transport and manufacturing sectors.")
    st.write("Cryptocurrency Market (e.g., Bitcoin, Ethereum)")
    st.write("Highly volatile and sometimes behaves independently, but can follow stock market trends during major economic events.")

if selected == "Filters":
     st.header("Crypto Oil Stock Market Analytics")
     filtered_df = pd.read_sql("select AVG(c.price_usd) AS bitcoin_avg_price, AVG(o.price_usd) AS oil_avg_price, AVG(s.close) AS sp500_avg_close, AVG(n.close) AS nifty_avg_close FROM crypto_price c JOIN oil_prices o ON c.Date = o.Date JOIN stock_prices s ON c.Date = s.Date AND s.ticker='^GSPC' JOIN stock_prices n  ON c.Date = n.Date AND n.ticker='^NSEI' WHERE c.coin_id='bitcoin' ",con=conn)
     btc_avg = filtered_df["bitcoin_avg_price"][0]
     oil_avg = filtered_df["oil_avg_price"][0]
     sp500_avg = filtered_df["sp500_avg_close"][0]
     nifty_avg = filtered_df["nifty_avg_close"][0]
     st.subheader("Market Average Prices")
     col1,col2,col3,col4 = st.columns(4)
     col1.metric("Bitcoin Avg Price", round(btc_avg,2))
     col2.metric("Oil Avg Price", round(oil_avg,2))
     col3.metric("S&P500 Avg Close", round(sp500_avg,2))
     col4.metric("NIFTY Avg Close", round(nifty_avg,2))
     st.subheader("Daily Market Snapshot")
     filtered_df = pd.read_sql("SELECT c.date, c.price_usd AS bitcoin_price, o.price_usd AS oil_price, s.close AS sp500_close, n.close AS nifty_close FROM crypto_price c JOIN oil_prices o ON c.date = o.date JOIN stock_prices s ON c.date = s.date AND s.ticker='^GSPC' JOIN stock_prices n ON c.date = n.date AND n.ticker='^NSEI' WHERE c.coin_id='bitcoin' GROUP BY c.date ORDER BY c.date; ",con=conn)
     st.dataframe(filtered_df)

if selected == "Queries":
     option = st.selectbox(
     "Ccryptocurrencies",
    (
     "1. Find the top 3 cryptocurrencies by market cap.",
     "2.List all coins where circulating supply exceeds 90% of total supply.",
     "3. Get coins that are within 10% of their all-time-high (ATH).",
     "4. Find the average market cap rank of coins with volume above $1B.",
     "5. Get the most recently updated coin."
     )
)
     if option == "1. Find the top 3 cryptocurrencies by market cap.":
         filtered_df = pd.read_sql("SELECT name, symbol, market_cap FROM Cryptocurrencies ORDER BY market_cap DESC LIMIT 3",con=conn)
         st.dataframe(filtered_df)
     if option == "2.List all coins where circulating supply exceeds 90% of total supply.":
         filtered_df = pd.read_sql("SELECT name, symbol, circulating_supply, total_supply FROM Cryptocurrencies WHERE circulating_supply >= 0.9 * total_supply;",con=conn)
         st.dataframe(filtered_df)
     if option == "3. Get coins that are within 10% of their all-time-high (ATH).":
         filtered_df = pd.read_sql("SELECT name, symbol, current_price, ath FROM cryptocurrencies WHERE CAST(current_price AS REAL) >= 0.9 * CAST(ath AS REAL);",con=conn)
         st.dataframe(filtered_df)
     if option == "4. Find the average market cap rank of coins with volume above $1B.":
         filtered_df = pd.read_sql("SELECT AVG(market_cap_rank) AS avg_market_cap_rank FROM cryptocurrencies WHERE Date > 1000000000;",con=conn)
         st.dataframe(filtered_df)
     if option == "5. Get the most recently updated coin.":
         filtered_df = pd.read_sql("SELECT  * FROM cryptocurrencies ORDER BY Date DESC LIMIT 1;",con=conn)
         st.dataframe(filtered_df)

#crypto_prices
#st.title("Crypto Prices")
if selected == "Queries":
     option = st.selectbox(
     "crypto_prices",
    (
     "1. Find the highest daily price of Bitcoin in the last 365 days.",
     "2. Calculate the average daily price of Ethereum in the past 1 year.",
     "3. Show the daily price trend of Bitcoin in January 2025",
     "4. Find the coin with the highest average price over 1 year.",
     "5. Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025."
     )
)
     if option == "1. Find the highest daily price of Bitcoin in the last 365 days.":
         crypto_prices = pd.read_sql("SELECT MAX(price_usd) AS highest_price FROM crypto_price WHERE coin_id = 'bitcoin';",con=conn)
         st.dataframe(crypto_prices)
     if option == "2. Calculate the average daily price of Ethereum in the past 1 year.":
         crypto_prices = pd.read_sql("SELECT AVG(price_usd) AS avg_price FROM crypto_price WHERE coin_id = 'ethereum'",con=conn)
         st.dataframe(crypto_prices)
     if option == "3. Show the daily price trend of Bitcoin in January 2025":
         crypto_prices = pd.read_sql(" SELECT date, price_usd FROM crypto_price WHERE coin_id = 'bitcoin' and date between '2025-01-01' and '2025-04-30' ",con = conn)
         st.dataframe(crypto_prices)
     if option == "4. Find the coin with the highest average price over 1 year.":
         crypto_prices = pd.read_sql("SELECT coin_id, AVG(price_usd) AS avg_price FROM crypto_price GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;",con=conn)
         st.dataframe(crypto_prices)
     if option == "5. Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.":
         crypto_prices = pd.read_sql("SELECT ((sep2025.price - sep2024.price) * 100.0 / sep2024.price) AS pct_change FROM (SELECT price_usd AS price FROM crypto_price WHERE coin_id = 'bitcoin' AND date BETWEEN '2024-09-01' AND '2024-09-30' ORDER BY date DESC LIMIT 1) AS sep2024,(SELECT price_usd AS price FROM crypto_price WHERE coin_id = 'bitcoin' AND date BETWEEN '2025-09-01' AND '2025-09-30' ORDER BY date DESC LIMIT 1) AS sep2025;",con=conn)
         st.dataframe(crypto_prices)

#st.title("Oil prices")
if selected == "Queries":

     option = st.selectbox(
    "Oil_prices",
    (
     "1. Find the highest oil price in the last 5 years.",
     "2. Get the average oil price per year.",
     "3. Show oil prices during COVID crash (March–April 2020).",
     "4. Find the lowest price of oil in the last 10 years.",
     "5. Calculate the volatility of oil prices (max-min difference per year).  "
     )
)

     if option == "1. Find the highest oil price in the last 5 years.":
         filtered_df = pd.read_sql("SELECT MAX(price_usd) AS highest_price FROM oil_prices WHERE date >= date('now','-5 years');",con=conn)
         st.dataframe(filtered_df)
     if option == "2. Get the average oil price per year.":
         filtered_df = pd.read_sql("SELECT strftime('%Y', date) AS year, AVG(price_usd) AS avg_price FROM oil_prices GROUP BY year ORDER BY year;",con=conn)
         st.dataframe(filtered_df)
     if option == "3. Show oil prices during COVID crash (March–April 2020).":
         filtered_df = pd.read_sql("SELECT date, price_usd FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' GROUP BY date ORDER BY date;",con=conn)
         st.dataframe(filtered_df)
     if option == "4. Find the lowest price of oil in the last 10 years.":
         filtered_df = pd.read_sql("SELECT MIN(price_usd) FROM oil_prices WHERE date >= date('now','-10 years');",con=conn)
         st.dataframe(filtered_df)
     if option == "5. Calculate the volatility of oil prices (max-min difference per year).":
         filtered_df = pd.read_sql("SELECT strftime('%Y', date) AS year, MAX(price_usd) - MIN(price_usd) AS volatility FROM oil_prices GROUP BY year ORDER BY year;",con=conn)
         st.dataframe(filtered_df)

#"stock_prices"
#st.title("stock_prices")
if selected == "Queries":

     option = st.selectbox(
    "stock_prices",
    (
     "1. Get all stock prices for a given ticker",
     "2. Find the highest closing price for NASDAQ (^IXIC)",
     "3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)",
     "4. Get monthly average closing price for each ticker",
     "5. Get average trading volume of NSEI in 2024"
     )
)

     if option == "1. Get all stock prices for a given ticker":
         all_stocks = pd.read_sql("SELECT * FROM stock_prices WHERE ticker='^NSEI';",con=conn)
         st.dataframe(all_stocks)
     if option == "2. Find the highest closing price for NASDAQ (^IXIC)":
         all_stocks = pd.read_sql("SELECT MAX(close) AS highest_close FROM stock_prices WHERE ticker='^IXIC';",con=conn)
         st.dataframe(all_stocks)
     if option == "3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)":
         all_stocks = pd.read_sql("SELECT date, high, low, (high-low) AS price_diff FROM stock_prices WHERE ticker='^GSPC' ORDER BY price_diff DESC LIMIT 5;",con=conn)
         st.dataframe(all_stocks)
     if option == "4. Get monthly average closing price for each ticker":
         all_stocks = pd.read_sql("SELECT strftime('%Y-%m', date) AS month, ticker, AVG(close) AS avg_close FROM stock_prices GROUP BY ticker, month ORDER BY ticker, month;",con=conn)
         st.dataframe(all_stocks)
     if option == "5. Get average trading volume of NSEI in 2024":
         all_stocks = pd.read_sql("SELECT AVG(volume) AS avg_volume FROM stock_prices WHERE ticker='^NSEI' AND strftime('%Y', date)='2024';",con=conn)
         st.dataframe(all_stocks)

if selected == "Queries":
     option = st.selectbox(
     "Join Query",
    (
     "1. Compare Bitcoin vs Oil average price in 2025.",
     "2. Check if Bitcoin moves with S&P 500 (correlation idea).",
     "3. Compare Ethereum and NASDAQ daily prices for 2025.",
     "4. Find days when oil price spiked and compare with Bitcoin price change.",
     "5. Compare top 3 coins daily price trend vs Nifty (^NSEI).",
     "6. Compare stock prices (^GSPC) with crude oil prices on the same dates",
     "7. Correlate Bitcoin closing price with crude oil closing price (same date)",
     "8. Compare NASDAQ (^IXIC) with Ethereum price trends",
     "9. Join top 3 crypto coins with stock indices for 2025",
     "10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison"
     )
)
     if option == "1. Compare Bitcoin vs Oil average price in 2025.":
         filtered_df = pd.read_sql("SELECT 'Bitcoin' AS Asset, AVG(price_usd) AS Avg_price_2025 FROM crypto_price WHERE strftime('%Y', date) = '2025' UNION ALL SELECT 'Oil' AS asset, AVG(price_usd) AS avg_price_2025 FROM oil_prices WHERE strftime('%Y', date) = '2025' ",con=conn)
         st.dataframe(filtered_df)
     if option == "2. Check if Bitcoin moves with S&P 500 (correlation idea).":
         filtered_df = pd.read_sql("SELECT s.date, s.close AS sp500_close, c.price_usd AS bitcoin_price FROM stock_prices s JOIN crypto_price c ON s.date = c.date WHERE s.ticker='^GSPC' AND c.coin_id='bitcoin' ORDER BY s.date",con=conn)
         st.dataframe(filtered_df)
     if option == "3. Compare Ethereum and NASDAQ daily prices for 2025.":
         filtered_df = pd.read_sql("SELECT s.date, s.close AS nasdaq_close, c.price_usd AS ethereum_price FROM stock_prices s JOIN crypto_price c ON s.date = c.date WHERE s.ticker='^IXIC' AND c.coin_id='ethereum' AND strftime('%Y', s.date)='2025' ORDER BY s.date",con=conn)
         st.dataframe(filtered_df)
     if option == "4. Find days when oil price spiked and compare with Bitcoin price change.":
         filtered_df = pd.read_sql(" SELECT o.date, o.price_usd AS oil_price, (o.price_usd - LAG(o.price_usd) OVER (ORDER BY o.date)) AS oil_change, c.price_usd AS bitcoin_price, (c.price_usd - LAG(c.price_usd) OVER (ORDER BY c.date)) AS bitcoin_change FROM oil_prices o LEFT JOIN crypto_price c ON o.date = c.date WHERE c.coin_id='bitcoin' ORDER BY o.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "5. Compare top 3 coins daily price trend vs Nifty (^NSEI).":
         filtered_df = pd.read_sql(" SELECT c.date, c.coin_id , c.price_usd AS crypto_price, s.close AS nifty_price FROM crypto_price c JOIN stock_prices s ON c.date = s.date WHERE c.coin_id IN ( SELECT coin_id FROM crypto_price GROUP BY coin_id ORDER BY AVG(price_usd) DESC LIMIT 3 ) AND s.ticker = '^NSEI' ORDER BY c.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "6. Compare stock prices (^GSPC) with crude oil prices on the same dates":
         filtered_df = pd.read_sql("SELECT s.date, s.close AS sp500_close, o.price_usd AS oil_price FROM stock_prices s LEFT JOIN oil_prices o ON s.date = o.date WHERE s.ticker='^GSPC' GROUP BY s.date ORDER BY s.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "7. Correlate Bitcoin closing price with crude oil closing price (same date)":
         filtered_df = pd.read_sql("SELECT c.date, c.price_usd AS bitcoin_price, o.price_usd AS oil_price FROM crypto_price c JOIN oil_prices o ON c.date = o.date WHERE c.coin_id='bitcoin' ORDER BY c.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "8. Compare NASDAQ (^IXIC) with Ethereum price trends":
         filtered_df = pd.read_sql("SELECT  s.date, s.close AS nasdaq_close, c.price_usd AS ethereum_price FROM stock_prices s JOIN crypto_price c ON s.date = c.date WHERE s.ticker='^IXIC' AND c.coin_id='ethereum' ORDER BY s.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "9. Join top 3 crypto coins with stock indices for 2025":
         filtered_df = pd.read_sql("SELECT c.date, c.coin_id, c.price_usd, s.ticker, s.close AS stock_close FROM crypto_price c JOIN stock_prices s ON c.date = s.date WHERE c.coin_id IN ('bitcoin','ethereum','tether') AND s.ticker IN ('^IXIC','^GSPC') AND strftime('%Y', c.date)='2025' ORDER BY c.date;",con=conn)
         st.dataframe(filtered_df)
     if option == "10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison":
         filtered_df = pd.read_sql("SELECT s.date, s.ticker, s.close AS stock_close, o.price_usd AS oil_price, c.price_usd AS bitcoin_price FROM stock_prices s JOIN oil_prices o ON s.date = o.date JOIN crypto_price c ON s.date = c.date WHERE s.ticker='^IXIC' AND c.coin_id='bitcoin' ORDER BY s.date;",con=conn)
         st.dataframe(filtered_df)

if selected == "Crypto Analysis":
    st.title("Cryptocurrency Price Dashboard")
# Select coin
    coin = st.selectbox(
    "Select Cryptocurrency",
    ["bitcoin","ethereum","tether"]
    )
    # Date filters
    start_date = st.date_input("Start Date")
    end_date = st.date_input("End Date")

# SQL Query
    query = """ SELECT date, price_usd FROM crypto_price WHERE coin_id = ? AND date BETWEEN ? AND ? ORDER BY date """
    df = pd.read_sql(query, conn, params=(coin, start_date, end_date))
# Show line chart
    st.subheader("Daily Price Trend")
    st.line_chart(df.set_index("date"))

# Show table
    st.subheader("Daily Price Table")
    st.dataframe(df)

Overwriting app.py

In [81]:
!streamlit run /content/app.py &>/content/logs.txt &

In [82]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://pale-fioricet-entitled-nam.trycloudflare.com

In [34]:
!pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [35]:
pd.read_sql("select * from oil_prices",con = conn)

      index        Date  price_usd
0      8569  2020-01-02      61.17
1      8570  2020-01-03      63.00
2      8571  2020-01-06      63.27
3      8572  2020-01-07      62.70
4      8573  2020-01-08      59.65
...     ...         ...        ...
1515  10084  2026-01-26      60.46
1516  10085  2026-01-27      62.04
1517  10086  2026-01-28      62.75
1518  10087  2026-01-29      64.77
1519  10088  2026-01-30      64.50

[1520 rows x 3 columns]

In [37]:
import sqlite3

conn = sqlite3.connect('ds.db')   # change the name of database accordingly
cursor = conn.cursor()

In [38]:
# Create a table
cursor.execute('''CREATE TABLE IF NOT EXISTS Cryptocurrencies (
    id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18, 6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(20, 6),
    total_supply DECIMAL(20, 6),
    ath DECIMAL(18, 6),
    atl DECIMAL(18, 6),
    date DATE
);

                ''')

In [39]:
data = list(cc.itertuples(index=False, name=None))

In [40]:
query = "INSERT INTO Cryptocurrencies ( id, symbol, name, current_price, market_cap, market_cap_rank, total_volume, circulating_supply, total_supply, ath, atl, date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"

cursor.executemany(query, data)

# Commit changes
conn.commit()
conn.close()

In [41]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('ds.db')   # change the name of database accordingly
cursor = conn.cursor()
df = pd.read_sql("SELECT * FROM Cryptocurrencies", conn)
df
conn.commit()
conn.close()

In [42]:
df

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,Date
0,0.0,bitcoin,btc,Bitcoin,68962.000000,1379567028201,1,5.269775e+10,2.000304e+07,2.000304e+07,126080.000000,67.810000,2026-03-27
1,1.0,ethereum,eth,Ethereum,2070.100000,249847592130,2,1.835476e+10,1.206915e+08,1.206915e+08,4946.050000,0.432979,2026-03-27
2,2.0,tether,usdt,Tether,0.999393,184107104081,3,7.983953e+10,1.842166e+11,1.896835e+11,1.320000,0.572521,2026-03-27
3,3.0,binancecoin,bnb,BNB,630.270000,85943924731,4,9.112300e+08,1.363573e+08,1.363573e+08,1369.990000,0.039818,2026-03-27
4,4.0,ripple,xrp,XRP,1.370000,83875239392,5,2.639369e+09,6.134458e+10,9.998570e+10,3.650000,0.002686,2026-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,meet48,idol,MEET48,0.024025,42820111,496,4.098798e+06,1.782229e+09,4.767829e+09,0.041778,0.010342,2026-03-27
996,NaN,uchain-2,ucn,UCHAIN,427.370000,42724456,497,2.597663e+06,1.000000e+05,1.000000e+05,1806.540000,23.780000,2026-03-27
997,NaN,frax-share,frax,Frax (prev. FXS),0.447343,42671752,498,1.462204e+06,9.538945e+07,9.968150e+07,42.800000,0.433406,2026-03-27
998,NaN,tellor,trb,Tellor Tributes,15.420000,42663607,499,8.273354e+06,2.765886e+06,2.841339e+06,593.090000,0.010014,2026-03-27
999,NaN,ai-companions,aic,AI Companions,0.042629,42643543,500,3.003850e+05,1.000000e+09,1.000000e+09,0.580508,0.037514,2026-03-27

In [51]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('ds.db')   # change the name of database accordingly
cursor = conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS Crypto_price (
    coin_id VARCHAR(50),
    date DATE,
    price_usd DECIMAL(18, 6),

    FOREIGN KEY (coin_id)
    REFERENCES Cryptocurrencies(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
             ''')

conn.commit()
conn.close()

In [54]:
data = list(crypto_prices.itertuples(index=False, name=None))

In [55]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ds.db')
cursor = conn.cursor()
# Insert query
query = "INSERT INTO Crypto_price (coin_id, date, price_usd) VALUES (?, ?,?)"

# Bulk insert
cursor.executemany(query, data)

# Commit changes
conn.commit()
conn.close()

In [57]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("ds.db")
df = pd.read_sql("SELECT coin_id,date,price_usd FROM Crypto_price", conn)
df

      coin_id        date     price_usd
0     bitcoin  2025-03-28  87227.271580
1     bitcoin  2025-03-29  84359.469155
2     bitcoin  2025-03-30  82679.172554
3     bitcoin  2025-03-31  82356.381112
4     bitcoin  2025-04-01  82514.093654
...       ...         ...           ...
2191   tether  2026-03-24      0.999728
2192   tether  2026-03-25      0.999546
2193   tether  2026-03-26      0.999616
2194   tether  2026-03-27      0.999378
2195   tether  2026-03-27      0.999401

[2196 rows x 3 columns]

In [58]:
df

      coin_id        date     price_usd
0     bitcoin  2025-03-28  87227.271580
1     bitcoin  2025-03-29  84359.469155
2     bitcoin  2025-03-30  82679.172554
3     bitcoin  2025-03-31  82356.381112
4     bitcoin  2025-04-01  82514.093654
...       ...         ...           ...
2191   tether  2026-03-24      0.999728
2192   tether  2026-03-25      0.999546
2193   tether  2026-03-26      0.999616
2194   tether  2026-03-27      0.999378
2195   tether  2026-03-27      0.999401

[2196 rows x 3 columns]

In [59]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ds.db')
cursor = conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS oil_prices (date DATE PRIMARY KEY, price_usd DECIMAL(18, 6))''')

conn.commit()
conn.close()

In [60]:
data = list(filtered_df.itertuples(index=False, name=None))

In [61]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ds.db')
cursor = conn.cursor()
# Insert query
query = "INSERT INTO oil_prices (date, price_usd) VALUES (?, ?)"

# Bulk insert
cursor.executemany(query, data)

# Commit changes
conn.commit()
conn.close()

In [62]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ds.db')
cursor = conn.cursor()
df = pd.read_sql("SELECT Date,price_usd FROM Oil_prices", conn)

print(df)

            Date  price_usd
0     2020-01-02      61.17
1     2020-01-03      63.00
2     2020-01-06      63.27
3     2020-01-07      62.70
4     2020-01-08      59.65
...          ...        ...
3035  2026-01-26      60.46
3036  2026-01-27      62.04
3037  2026-01-28      62.75
3038  2026-01-29      64.77
3039  2026-01-30      64.50

[3040 rows x 2 columns]

In [63]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("ds.db")
cursor = conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS Stock_prices (
    date DATE,
    open DECIMAL(18, 6),
    high DECIMAL(18, 6),
    low DECIMAL(18, 6),
    close DECIMAL(18, 6),
    volume BIGINT,
    ticker VARCHAR(20)

);              ''')

In [64]:
data = list(all_stocks.itertuples(index=False, name=None))

In [65]:

# Insert query
query = "INSERT INTO Stock_prices (date,open, high, low, close,volume, ticker) VALUES (?, ?, ?, ?, ?, ?, ?)"

# Bulk insert
cursor.executemany(query, data)

# Commit changes
conn.commit()
conn.close()

In [66]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ds.db')
cursor = conn.cursor()
df = pd.read_sql("SELECT * FROM Stock_prices", conn)
print(df)
conn.commit()
conn.close()

      index        Date          Open          High           Low  \
0       1.0  2020-01-02   3244.669922   3258.139893   3235.530029
1       2.0  2020-01-03   3226.360107   3246.149902   3222.340088
2       3.0  2020-01-06   3217.550049   3246.840088   3214.639893
3       4.0  2020-01-07   3241.860107   3244.909912   3232.429932
4       5.0  2020-01-08   3238.590088   3267.070068   3236.669922
...     ...         ...           ...           ...           ...
8613    NaN  2025-09-23  25209.000000  25261.900391  25084.650391
8614    NaN  2025-09-24  25108.750000  25149.849609  25027.449219
8615    NaN  2025-09-25  25034.500000  25092.699219  24878.300781
8616    NaN  2025-09-26  24818.550781  24868.599609  24629.449219
8617    NaN  2025-09-29  24728.550781  24791.300781  24606.199219

             Close        Volume Ticker
0      3257.850098  3.459930e+09  ^GSPC
1      3234.850098  3.484700e+09  ^GSPC
2      3246.280029  3.702460e+09  ^GSPC
3      3237.179932  3.435910e+09  ^GSPC
4      3253.050049  3.726840e+09  ^GSPC
...            ...           ...    ...
8613  25169.500000  2.992000e+05  ^NSEI
8614  25056.900391  2.444000e+05  ^NSEI
8615  24890.849609  3.425000e+05  ^NSEI
8616  24654.699219  2.915000e+05  ^NSEI
8617  24634.900391  3.944000e+05  ^NSEI

[8618 rows x 8 columns]

In [67]:
df

,index,Date,Open,High,Low,Close,Volume,Ticker
0,1.0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,2.0,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,3.0,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,4.0,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,5.0,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...,...
8613,NaN,2025-09-23,25209.000000,25261.900391,25084.650391,25169.500000,2.992000e+05,^NSEI
8614,NaN,2025-09-24,25108.750000,25149.849609,25027.449219,25056.900391,2.444000e+05,^NSEI
8615,NaN,2025-09-25,25034.500000,25092.699219,24878.300781,24890.849609,3.425000e+05,^NSEI
8616,NaN,2025-09-26,24818.550781,24868.599609,24629.449219,24654.699219,2.915000e+05,^NSEI
8617,NaN,2025-09-29,24728.550781,24791.300781,24606.199219,24634.900391,3.944000e+05,^NSEI